"""Create models

Revision ID: dca0a7df5933
Revises: 
Create Date: 2024-06-03 13:04:26.483134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dca0a7df5933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Role_id', table_name='Role')
    op.create_foreign_key(None, 'User', 'UsersGroup', ['group_id'], ['id'])
    op.create_foreign_key(None, 'User', 'Role', ['role_id'], ['id'])
    op.drop_column('User', 'group_name')
    op.drop_column('User', 'role_name')
    op.drop_index('idx_username', table_name='UsersGroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_username', 'UsersGroup', ['username'], unique=False)
    op.add_column('User', sa.Column('role_name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('User', sa.Column('group_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_index('ix_Role_id', 'Role', ['id'], unique=False)
    # ### end Alembic commands ###
